export const MINES_EVENTS = {
  join: 'mines:join',
  joinError: 'mines:error:join',
  state: 'mines:state',
  gameNew: 'mines:game:new',
  playerJoined: 'mines:player:joined',
  playerLeft: 'mines:player:left',
  chatMessage: 'mines:chat:message',
  chatTyping: 'mines:chat:typing',
  move: 'mines:move',
  playerMoved: 'mines:player:moved',
  reveal: 'mines:cell:reveal',
  cellsRevealed: 'mines:cells:revealed',
  flag: 'mines:cell:flag',
  cellFlagged: 'mines:cell:flagged',
  bombExploded: 'mines:bomb:exploded',
  gameOver: 'mines:game:over',
  chatSend: 'mines:chat:send',
};

export const PAINT_EVENTS = {
  join: 'paint:join',
  joinError: 'paint:error:join',
  state: 'paint:state',
  playerJoined: 'paint:player:joined',
  playerLeft: 'paint:player:left',
  chatMessage: 'paint:chat:message',
  chatTyping: 'paint:chat:typing',
  move: 'paint:move',
  playerMoved: 'paint:player:moved',
  place: 'paint:pixel:place',
  pixel: 'paint:pixel',
  chatSend: 'paint:chat:send',
};

export const SKELETON_EVENTS = {
  join: 'skeleton:join',
  joinError: 'skeleton:error:join',
  state: 'skeleton:state',
  playerJoined: 'skeleton:player:joined',
  playerLeft: 'skeleton:player:left',
  move: 'skeleton:move',
  playerMoved: 'skeleton:player:moved',
  action: 'skeleton:action',
  actionApplied: 'skeleton:action:applied',
  chatMessage: 'skeleton:chat:message',
  chatTyping: 'skeleton:chat:typing',
  chatSend: 'skeleton:chat:send',
};

export const SNAKE_EVENTS = {
  join: 'snake:join',
  joinError: 'snake:error:join',
  state: 'snake:state',
  playerJoined: 'snake:player:joined',
  playerLeft: 'snake:player:left',
  chatMessage: 'snake:chat:message',
  chatTyping: 'snake:chat:typing',
  turn: 'snake:turn',
  tick: 'snake:tick',
  playerDied: 'snake:player:died',
  chatSend: 'snake:chat:send',
};
